[GLOBAL]
pants_version = "2.17.0"

backend_packages = [
    "pants.backend.build_files.fmt.black",
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.experimental.python.lint.ruff",
    "pants.backend.experimental.python.typecheck.pyright" # TODO enable when this is fixed https://github.com/pantsbuild/pants/issues/19778

    # NOTE: if you add non-python backends you may need to update the cache settings in the CI pipeline, see https://support.atlassian.com/bitbucket-cloud/docs/cache-dependencies
]

[source]
root_patterns = [
    "/src"
]

[python]
interpreter_constraints = ['==%(env.PYTHON_VERSION)s.*']
enable_resolves = true

[python.resolves]
python-default = "dependencies/requirements.lock"

[test]
use_coverage = true

[coverage-py]
report = ["html"]
output_dir = "coverage_report"
global_report = true

[anonymous-telemetry]
enabled = true
repo_id = "abf04ff0-cedf-4b3a-85d1-49a35011c646"
