[tool.black]
line-length = 120


[tool.ruff]
# Enable the pycodestyle (`E`), Pyflakes (`F`), isort (I), pep8-naming (N), pyupgrade (UP) rules by default.
select = ["E", "F", "I", "N", "UP"]

ignore = [
    "E501" # line length, defer to black auto-formatting (which doesn't always wrap comments)
]

# Allow autofix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Exclude a variety of commonly ignored directories.
exclude = [
    ".git",
    ".pants.d",
    ".ruff_cache",
    "__pypackages__",
    "_build",
    "build",
    "dist"
]
per-file-ignores = {}

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

# Assume Python 3.11
target-version = "py311"
