python_requirements(
    resolve="python-default",
    module_mapping={
        # Required for now due to https://github.com/pantsbuild/pants/issues/19761
        "cattrs": ("cattr", "cattrs")
    },
)
